#### Microdados do Censo da Educação Superior 2020.

#### Gerar arquivos e dados apenas dos municípios do Alto Tiête.

In [1]:
import numpy as np
import pandas as pd

In [2]:
arquivo1=True

if (arquivo1):
    ## Arquivo 1
    print('Trabalhando no arquivo: {}.'.format('MICRODADOS_CADASTRO_IES_2020.zip'))
    arquivos={'entrada':'MICRODADOS_CADASTRO_IES_2020.zip', 'saida':'MICRODADOS_CADASTRO_IES_2020_ALTO_TIETE.csv'}
    atr_selecao='NO_MUNICIPIO_IES'
    drop_columns=['NU_ANO_CENSO','NO_REGIAO_IES','CO_REGIAO_IES','NO_UF_IES','SG_UF_IES','CO_UF_IES','IN_CAPITAL_IES',
                  'NO_MESORREGIAO_IES','CO_MESORREGIAO_IES',
                  'DS_ENDERECO_IES','DS_NUMERO_ENDERECO_IES','DS_COMPLEMENTO_ENDERECO_IES','NO_BAIRRO_IES','NU_CEP_IES'
                 ]
else:
    ## Arquivo 2
    print('Trabalhando no arquivo: {}.'.format('MICRODADOS_CADASTRO_CURSOS_2020.zip'))
    arquivos={'entrada':'MICRODADOS_CADASTRO_CURSOS_2020.zip', 'saida':'MICRODADOS_CADASTRO_CURSOS_2020_ALTO_TIETE.csv'}
    atr_selecao='NO_MUNICIPIO'
    drop_columns=['NU_ANO_CENSO','NO_REGIAO','CO_REGIAO','NO_UF','SG_UF','CO_UF']

Trabalhando no arquivo: MICRODADOS_CADASTRO_IES_2020.zip.

In [3]:
ces=pd.read_csv('./Dados/'+arquivos['entrada'],
            sep=';',
            header=0,
            encoding='latin-1',
            low_memory=False,
            #on_bad_lines='skip'
            compression='zip'
            )

In [4]:
ces.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2457 entries, 0 to 2456
Data columns (total 81 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NU_ANO_CENSO                    2457 non-null   int64
 1   NO_REGIAO_IES                   2457 non-null   object
 2   CO_REGIAO_IES                   2457 non-null   int64
 3   NO_UF_IES                       2457 non-null   object
 4   SG_UF_IES                       2457 non-null   object
 5   CO_UF_IES                       2457 non-null   int64
 6   NO_MUNICIPIO_IES                2457 non-null   object
 7   CO_MUNICIPIO_IES                2457 non-null   int64
 8   IN_CAPITAL_IES                  2457 non-null   int64
 9   NO_MESORREGIAO_IES              2457 non-null   object
 10  CO_MESORREGIAO_IES              2457 non-null   int64
 11  NO_MICRORREGIAO_IES             2457 non-null   object
 12  CO_MICRORREGIAO_IES             2457 non-null   int64
 13  TP_ORGANIZACAO_ACADEMICA        2457 non-null   int64
 14  TP_CATEGORIA_ADMINISTRATIVA     2457 non-null   int64
 15  NO_MANTENEDORA                  2457 non-null   object
 16  CO_MANTENEDORA                  2457 non-null   int64
 17  CO_IES                          2457 non-null   int64
 18  NO_IES                          2457 non-null   object
 19  SG_IES                          2046 non-null   object
 20  DS_ENDERECO_IES                 2457 non-null   object
 21  DS_NUMERO_ENDERECO_IES          2456 non-null   object
 22  DS_COMPLEMENTO_ENDERECO_IES     2456 non-null   object
 23  NO_BAIRRO_IES                   2457 non-null   object
 24  NU_CEP_IES                      2413 non-null   float64
 25  QT_TEC_TOTAL                    2457 non-null   int64
 26  QT_TEC_FUNDAMENTAL_INCOMP_FEM   2457 non-null   int64
 27  QT_TEC_FUNDAMENTAL_INCOMP_MASC  2457 non-null   int64
 28  QT_TEC_FUNDAMENTAL_COMP_FEM     2457 non-null   int64
 29  QT_TEC_FUNDAMENTAL_COMP_MASC    2457 non-null   int64
 30  QT_TEC_MEDIO_FEM                2457 non-null   int64
 31  QT_TEC_MEDIO_MASC               2457 non-null   int64
 32  QT_TEC_SUPERIOR_FEM             2457 non-null   int64
 33  QT_TEC_SUPERIOR_MASC            2457 non-null   int64
 34  QT_TEC_ESPECIALIZACAO_FEM       2457 non-null   int64
 35  QT_TEC_ESPECIALIZACAO_MASC      2457 non-null   int64
 36  QT_TEC_MESTRADO_FEM             2457 non-null   int64
 37  QT_TEC_MESTRADO_MASC            2457 non-null   int64
 38  QT_TEC_DOUTORADO_FEM            2457 non-null   int64
 39  QT_TEC_DOUTORADO_MASC           2457 non-null   int64
 40  IN_ACESSO_PORTAL_CAPES          2457 non-null   int64
 41  IN_ACESSO_OUTRAS_BASES          2457 non-null   int64
 42  IN_ASSINA_OUTRA_BASE            2457 non-null   int64
 43  IN_REPOSITORIO_INSTITUCIONAL    2457 non-null   int64
 44  IN_BUSCA_INTEGRADA              2457 non-null   int64
 45  IN_SERVICO_INTERNET             2457 non-null   int64
 46  IN_PARTICIPA_REDE_SOCIAL        2457 non-null   int64
 47  IN_CATALOGO_ONLINE              2457 non-null   int64
 48  QT_PERIODICO_ELETRONICO         2457 non-null   int64
 49  QT_LIVRO_ELETRONICO             2457 non-null   int64
 50  QT_DOC_TOTAL                    2457 non-null   int64
 51  QT_DOC_EXE                      2457 non-null   int64
 52  QT_DOC_EX_FEMI                  2457 non-null   int64
 53  QT_DOC_EX_MASC                  2457 non-null   int64
 54  QT_DOC_EX_SEM_GRAD              2457 non-null   int64
 55  QT_DOC_EX_GRAD                  2457 non-null   int64
 56  QT_DOC_EX_ESP                   2457 non-null   int64
 57  QT_DOC_EX_MEST                  2457 non-null   int64
 58  QT_DOC_EX_DOUT                  2457 non-null   int64
 59  QT_DOC_EX_INT                   2457 non-null   int64
 60  QT_DOC_EX_INT_DE                2457 non-null   int64
 61  QT_DOC_EX_INT_SEM_DE            2457 non-null   int64
 62  QT_DOC_EX_PARC                  2457 non-null   int64
 63  QT_DOC_EX_HOR                   2457 non-null   int64
 64  QT_DOC_EX_0_29                  2457 non-null   int64
 65  QT_DOC_EX_30_34                 2457 non-null   int64
 66  QT_DOC_EX_35_39                 2457 non-null   int64
 67  QT_DOC_EX_40_44                 2457 non-null   int64
 68  QT_DOC_EX_45_49                 2457 non-null   int64
 69  QT_DOC_EX_50_54                 2457 non-null   int64
 70  QT_DOC_EX_55_59                 2457 non-null   int64
 71  QT_DOC_EX_60_MAIS               2457 non-null   int64
 72  QT_DOC_EX_BRANCA                2457 non-null   int64
 73  QT_DOC_EX_PRETA                 2457 non-null   int64
 74  QT_DOC_EX_PARDA                 2457 non-null   int64
 75  QT_DOC_EX_AMARELA               2457 non-null   int64
 76  QT_DOC_EX_INDIGENA              2457 non-null   int64
 77  QT_DOC_EX_COR_ND                2457 non-null   int64
 78  QT_DOC_EX_BRA                   2457 non-null   int64
 79  QT_DOC_EX_EST                   2457 non-null   int64
 80  QT_DOC_EX_COM_DEFICIENCIA       2457 non-null   int64
dtypes: float64(1), int64(67), object(13)
memory usage: 1.5+ MB

In [5]:
ces

,NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,...,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
0,2020,Centro-Oeste,5,Mato Grosso,MT,51,Cuiabá,5103403,1,Centro-Sul Mato-grossense,...,177,890,64,348,38,6,148,1460,34,2
1,2020,Centro-Oeste,5,Distrito Federal,DF,53,Brasília,5300108,1,Distrito Federal,...,445,1741,87,439,60,5,437,2617,152,6
2,2020,Nordeste,2,Sergipe,SE,28,São Cristóvão,2806701,0,Leste Sergipano,...,151,159,30,254,5,2,1321,1744,27,4
3,2020,Norte,1,Amazonas,AM,13,Manaus,1302603,1,Centro Amazonense,...,185,53,7,64,2,4,1623,1752,1,0
4,2020,Nordeste,2,Piauí,PI,22,Teresina,2211001,1,Centro-Norte Piauiense,...,213,99,39,182,0,2,1089,1411,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2452,2020,Centro-Oeste,5,Goiás,GO,52,Catalão,5205109,0,Sul Goiano,...,11,193,12,63,5,0,67,334,6,0
2453,2020,Nordeste,2,Pernambuco,PE,26,Garanhuns,2606002,0,Agreste Pernambucano,...,5,7,0,1,0,0,166,174,0,0
2454,2020,Nordeste,2,Piauí,PI,22,Parnaíba,2207702,0,Norte Piauiense,...,15,18,3,29,1,0,186,237,0,0
2455,2020,Centro-Oeste,5,Goiás,GO,52,Jataí,5211909,0,Sul Goiano,...,10,150,16,57,4,0,154,378,3,1
2456,2020,Centro-Oeste,5,Mato Grosso,MT,51,Rondonópolis,5107602,0,Sudeste Mato-grossense,...,19,181,11,74,5,1,23,290,5,2

In [6]:
ces.drop(labels=drop_columns, axis=1, inplace=True)

cidades=['Arujá','Biritiba Mirim','Ferraz de Vasconcelos','Guararema','Guarulhos','Itaquaquecetuba','Mogi das Cruzes',
         'Poá','Salesópolis','Santa Isabel','Suzano']
cesat=ces[(ces[atr_selecao].isin(cidades))]
cesat.reset_index(inplace=True, drop=True, level=0)

cesat

,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,...,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
0,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,5,CLUBE NAUTICO MOGIANO,175,243,FACULDADE DO CLUBE NÁUTICO MOGIANO,...,3,22,0,0,0,0,0,22,0,2
1,Guarulhos,3518800,Guarulhos,59,1,5,SOCIEDADE PAULISTA DE ENSINO E PESQUISA S/S LTDA,16298,481,Universidade Universus Veritas Guarulhos,...,43,320,5,120,5,1,1,452,0,0
2,Guarulhos,3518800,Guarulhos,59,2,5,SOCIEDADE GUARULHENSE DE EDUCACAO,333,483,CENTRO UNIVERSITÁRIO METROPOLITANO DE SÃO PAULO,...,28,49,0,5,0,0,3,57,0,1
3,Mogi das Cruzes,3530607,Mogi das Cruzes,62,1,4,ORGANIZACAO MOGIANA DE EDUCACAO E CULTURA SOCI...,362,521,UNIVERSIDADE DE MOGI DAS CRUZES,...,171,623,9,57,29,0,27,732,13,9
4,Mogi das Cruzes,3530607,Mogi das Cruzes,62,2,4,SOCIEDADE EDUCACIONAL BRAZ CUBAS LTDA.,365,526,CENTRO UNIVERSITÁRIO BRAZ CUBAS,...,58,238,7,19,5,0,66,331,4,0
5,Suzano,3552502,Mogi das Cruzes,62,3,5,UNIESP S.A,16134,1313,FACULDADE DE SUZANO,...,5,29,1,4,1,0,5,40,0,0
6,Guarulhos,3518800,Guarulhos,59,2,4,EDVAC SERVICOS EDUCACIONAIS LTDA,1243,1892,Centro Universitário de Excelência Eniac,...,10,41,0,9,0,1,42,92,1,0
7,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,5,ASSOCIACAO CULTURAL PAULO VI,1557,2389,FACULDADE DE FILOSOFIA E TEOLOGIA PAULO VI,...,8,21,0,3,0,0,2,23,3,0
8,Guarulhos,3518800,Guarulhos,59,3,4,UNIESP S.A,16134,2530,FACULDADE DE GUARULHOS,...,3,20,1,2,0,0,7,30,0,1
9,Guarulhos,3518800,Guarulhos,59,2,4,UNIFAVENI CENTRO UNIVERSITARIO FAVENI LTDA,17427,3294,CENTRO UNIVERSITÁRIO FAVENI,...,15,60,1,10,0,0,21,90,2,0
10,Guarulhos,3518800,Guarulhos,59,3,4,ANHANGUERA EDUCACIONAL PARTICIPACOES S/A,16452,3603,FACULDADE ANHANGUERA DE GUARULHOS,...,18,118,5,17,4,1,1,145,1,2
11,Guarulhos,3518800,Guarulhos,59,3,4,E.E.S.R.G.- EMPRESA DE ENSINO SUPERIOR REUNIDA...,17911,13752,FACULDADE DOM RICARDO,...,0,6,1,1,0,0,2,10,0,0
12,Suzano,3552502,Mogi das Cruzes,62,3,5,UNIPIAGET/BRASIL,13938,14715,FACULDADE PIAGET,...,3,59,0,7,0,0,2,68,0,0
13,Guarulhos,3518800,Guarulhos,59,3,4,PRO-FAC ENSINO SUPERIOR LTDA - ME,13766,14727,FACULDADE PROGRESSO,...,9,31,3,4,0,1,2,39,2,1
14,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,15576,Faculdade de Tecnologia de Mogi das Cruzes,...,14,64,3,6,2,1,0,76,0,0
15,Itaquaquecetuba,3523107,Mogi das Cruzes,62,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,15639,Faculdade de Tecnologia de Itaquaquecetuba,...,11,43,4,6,2,0,1,56,0,0
16,Guarulhos,3518800,Guarulhos,59,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,15752,Faculdade de Tecnologia de Guarulhos,...,17,55,2,8,0,0,11,76,0,0
17,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,4,INSTITUTO EDUCATIEHOOG DE ENSINO E PESQUISA LI...,15563,16901,INSTITUTO EDUCATIE,...,4,13,0,0,0,0,2,15,0,0
18,Arujá,3503901,Guarulhos,59,3,5,JOVENS DA VERDADE ASSOCIACAO CIVIL,15953,18288,Faculdade Latino-americana,...,3,13,1,0,0,0,0,14,0,0
19,Guarulhos,3518800,Guarulhos,59,3,4,FACULDADE DE ENSINO GUARULHENSE SS LTDA,16736,21822,FACULDADE TORRICELLI,...,4,9,0,4,0,0,0,13,0,0
20,Guarulhos,3518800,Guarulhos,59,3,5,ASSOCIACAO EDUCACIONAL NOVE DE JULHO,222,22314,FACULDADE NOVE DE JULHO GUARULHOS,...,1,19,1,2,1,0,0,23,0,1
21,Ferraz de Vasconcelos,3515707,Mogi das Cruzes,62,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,23700,Faculdade de Tecnologia de Ferraz de Vasconcelos,...,4,34,4,10,1,0,1,50,0,0

In [7]:
cesat.to_csv('./Dados/'+arquivos['saida'],
             sep=';',
             header=True,
             mode='w',
             encoding='latin-1',
             #compression='zip',
             index=False
            )

In [8]:
ces2=pd.read_csv('./Dados/'+arquivos['saida'],
            sep=';',
            header=0,
            encoding='latin-1',
            low_memory=False,
            #on_bad_lines='skip'
            #compression='zip'
            )

In [9]:
ces2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 67 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NO_MUNICIPIO_IES                22 non-null     object
 1   CO_MUNICIPIO_IES                22 non-null     int64
 2   NO_MICRORREGIAO_IES             22 non-null     object
 3   CO_MICRORREGIAO_IES             22 non-null     int64
 4   TP_ORGANIZACAO_ACADEMICA        22 non-null     int64
 5   TP_CATEGORIA_ADMINISTRATIVA     22 non-null     int64
 6   NO_MANTENEDORA                  22 non-null     object
 7   CO_MANTENEDORA                  22 non-null     int64
 8   CO_IES                          22 non-null     int64
 9   NO_IES                          22 non-null     object
 10  SG_IES                          19 non-null     object
 11  QT_TEC_TOTAL                    22 non-null     int64
 12  QT_TEC_FUNDAMENTAL_INCOMP_FEM   22 non-null     int64
 13  QT_TEC_FUNDAMENTAL_INCOMP_MASC  22 non-null     int64
 14  QT_TEC_FUNDAMENTAL_COMP_FEM     22 non-null     int64
 15  QT_TEC_FUNDAMENTAL_COMP_MASC    22 non-null     int64
 16  QT_TEC_MEDIO_FEM                22 non-null     int64
 17  QT_TEC_MEDIO_MASC               22 non-null     int64
 18  QT_TEC_SUPERIOR_FEM             22 non-null     int64
 19  QT_TEC_SUPERIOR_MASC            22 non-null     int64
 20  QT_TEC_ESPECIALIZACAO_FEM       22 non-null     int64
 21  QT_TEC_ESPECIALIZACAO_MASC      22 non-null     int64
 22  QT_TEC_MESTRADO_FEM             22 non-null     int64
 23  QT_TEC_MESTRADO_MASC            22 non-null     int64
 24  QT_TEC_DOUTORADO_FEM            22 non-null     int64
 25  QT_TEC_DOUTORADO_MASC           22 non-null     int64
 26  IN_ACESSO_PORTAL_CAPES          22 non-null     int64
 27  IN_ACESSO_OUTRAS_BASES          22 non-null     int64
 28  IN_ASSINA_OUTRA_BASE            22 non-null     int64
 29  IN_REPOSITORIO_INSTITUCIONAL    22 non-null     int64
 30  IN_BUSCA_INTEGRADA              22 non-null     int64
 31  IN_SERVICO_INTERNET             22 non-null     int64
 32  IN_PARTICIPA_REDE_SOCIAL        22 non-null     int64
 33  IN_CATALOGO_ONLINE              22 non-null     int64
 34  QT_PERIODICO_ELETRONICO         22 non-null     int64
 35  QT_LIVRO_ELETRONICO             22 non-null     int64
 36  QT_DOC_TOTAL                    22 non-null     int64
 37  QT_DOC_EXE                      22 non-null     int64
 38  QT_DOC_EX_FEMI                  22 non-null     int64
 39  QT_DOC_EX_MASC                  22 non-null     int64
 40  QT_DOC_EX_SEM_GRAD              22 non-null     int64
 41  QT_DOC_EX_GRAD                  22 non-null     int64
 42  QT_DOC_EX_ESP                   22 non-null     int64
 43  QT_DOC_EX_MEST                  22 non-null     int64
 44  QT_DOC_EX_DOUT                  22 non-null     int64
 45  QT_DOC_EX_INT                   22 non-null     int64
 46  QT_DOC_EX_INT_DE                22 non-null     int64
 47  QT_DOC_EX_INT_SEM_DE            22 non-null     int64
 48  QT_DOC_EX_PARC                  22 non-null     int64
 49  QT_DOC_EX_HOR                   22 non-null     int64
 50  QT_DOC_EX_0_29                  22 non-null     int64
 51  QT_DOC_EX_30_34                 22 non-null     int64
 52  QT_DOC_EX_35_39                 22 non-null     int64
 53  QT_DOC_EX_40_44                 22 non-null     int64
 54  QT_DOC_EX_45_49                 22 non-null     int64
 55  QT_DOC_EX_50_54                 22 non-null     int64
 56  QT_DOC_EX_55_59                 22 non-null     int64
 57  QT_DOC_EX_60_MAIS               22 non-null     int64
 58  QT_DOC_EX_BRANCA                22 non-null     int64
 59  QT_DOC_EX_PRETA                 22 non-null     int64
 60  QT_DOC_EX_PARDA                 22 non-null     int64
 61  QT_DOC_EX_AMARELA               22 non-null     int64
 62  QT_DOC_EX_INDIGENA              22 non-null     int64
 63  QT_DOC_EX_COR_ND                22 non-null     int64
 64  QT_DOC_EX_BRA                   22 non-null     int64
 65  QT_DOC_EX_EST                   22 non-null     int64
 66  QT_DOC_EX_COM_DEFICIENCIA       22 non-null     int64
dtypes: int64(62), object(5)
memory usage: 11.6+ KB

In [10]:
cesat

,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,...,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
0,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,5,CLUBE NAUTICO MOGIANO,175,243,FACULDADE DO CLUBE NÁUTICO MOGIANO,...,3,22,0,0,0,0,0,22,0,2
1,Guarulhos,3518800,Guarulhos,59,1,5,SOCIEDADE PAULISTA DE ENSINO E PESQUISA S/S LTDA,16298,481,Universidade Universus Veritas Guarulhos,...,43,320,5,120,5,1,1,452,0,0
2,Guarulhos,3518800,Guarulhos,59,2,5,SOCIEDADE GUARULHENSE DE EDUCACAO,333,483,CENTRO UNIVERSITÁRIO METROPOLITANO DE SÃO PAULO,...,28,49,0,5,0,0,3,57,0,1
3,Mogi das Cruzes,3530607,Mogi das Cruzes,62,1,4,ORGANIZACAO MOGIANA DE EDUCACAO E CULTURA SOCI...,362,521,UNIVERSIDADE DE MOGI DAS CRUZES,...,171,623,9,57,29,0,27,732,13,9
4,Mogi das Cruzes,3530607,Mogi das Cruzes,62,2,4,SOCIEDADE EDUCACIONAL BRAZ CUBAS LTDA.,365,526,CENTRO UNIVERSITÁRIO BRAZ CUBAS,...,58,238,7,19,5,0,66,331,4,0
5,Suzano,3552502,Mogi das Cruzes,62,3,5,UNIESP S.A,16134,1313,FACULDADE DE SUZANO,...,5,29,1,4,1,0,5,40,0,0
6,Guarulhos,3518800,Guarulhos,59,2,4,EDVAC SERVICOS EDUCACIONAIS LTDA,1243,1892,Centro Universitário de Excelência Eniac,...,10,41,0,9,0,1,42,92,1,0
7,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,5,ASSOCIACAO CULTURAL PAULO VI,1557,2389,FACULDADE DE FILOSOFIA E TEOLOGIA PAULO VI,...,8,21,0,3,0,0,2,23,3,0
8,Guarulhos,3518800,Guarulhos,59,3,4,UNIESP S.A,16134,2530,FACULDADE DE GUARULHOS,...,3,20,1,2,0,0,7,30,0,1
9,Guarulhos,3518800,Guarulhos,59,2,4,UNIFAVENI CENTRO UNIVERSITARIO FAVENI LTDA,17427,3294,CENTRO UNIVERSITÁRIO FAVENI,...,15,60,1,10,0,0,21,90,2,0
10,Guarulhos,3518800,Guarulhos,59,3,4,ANHANGUERA EDUCACIONAL PARTICIPACOES S/A,16452,3603,FACULDADE ANHANGUERA DE GUARULHOS,...,18,118,5,17,4,1,1,145,1,2
11,Guarulhos,3518800,Guarulhos,59,3,4,E.E.S.R.G.- EMPRESA DE ENSINO SUPERIOR REUNIDA...,17911,13752,FACULDADE DOM RICARDO,...,0,6,1,1,0,0,2,10,0,0
12,Suzano,3552502,Mogi das Cruzes,62,3,5,UNIPIAGET/BRASIL,13938,14715,FACULDADE PIAGET,...,3,59,0,7,0,0,2,68,0,0
13,Guarulhos,3518800,Guarulhos,59,3,4,PRO-FAC ENSINO SUPERIOR LTDA - ME,13766,14727,FACULDADE PROGRESSO,...,9,31,3,4,0,1,2,39,2,1
14,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,15576,Faculdade de Tecnologia de Mogi das Cruzes,...,14,64,3,6,2,1,0,76,0,0
15,Itaquaquecetuba,3523107,Mogi das Cruzes,62,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,15639,Faculdade de Tecnologia de Itaquaquecetuba,...,11,43,4,6,2,0,1,56,0,0
16,Guarulhos,3518800,Guarulhos,59,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,15752,Faculdade de Tecnologia de Guarulhos,...,17,55,2,8,0,0,11,76,0,0
17,Mogi das Cruzes,3530607,Mogi das Cruzes,62,3,4,INSTITUTO EDUCATIEHOOG DE ENSINO E PESQUISA LI...,15563,16901,INSTITUTO EDUCATIE,...,4,13,0,0,0,0,2,15,0,0
18,Arujá,3503901,Guarulhos,59,3,5,JOVENS DA VERDADE ASSOCIACAO CIVIL,15953,18288,Faculdade Latino-americana,...,3,13,1,0,0,0,0,14,0,0
19,Guarulhos,3518800,Guarulhos,59,3,4,FACULDADE DE ENSINO GUARULHENSE SS LTDA,16736,21822,FACULDADE TORRICELLI,...,4,9,0,4,0,0,0,13,0,0
20,Guarulhos,3518800,Guarulhos,59,3,5,ASSOCIACAO EDUCACIONAL NOVE DE JULHO,222,22314,FACULDADE NOVE DE JULHO GUARULHOS,...,1,19,1,2,1,0,0,23,0,1
21,Ferraz de Vasconcelos,3515707,Mogi das Cruzes,62,3,2,CENTRO ESTADUAL DE EDUCACAO TECNOLOGICA PAULA ...,33,23700,Faculdade de Tecnologia de Ferraz de Vasconcelos,...,4,34,4,10,1,0,1,50,0,0

#### Descrição dos atributos.

In [11]:
print(arquivo1)
if (arquivo1):
    desc=pd.read_csv('./Anexos/ANEXO I - Dicionário de Dados/cadastro_ies.csv',
                    sep=';',
                    header=0,
                    encoding='latin-1',
                    low_memory=True
                    #on_bad_lines='skip'
                    )
else:
    desc=pd.read_csv('./Anexos/ANEXO I - Dicionário de Dados/cadastro_cursos.csv',
                    sep=';',
                    header=0,
                    encoding='latin-1',
                    low_memory=True
                    #on_bad_lines='skip'
                    )

True

In [12]:
desc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 85 non-null     object
 1   Alteração de nomenclatura  84 non-null     object
 2   Unnamed: 2                 82 non-null     object
 3   Unnamed: 3                 82 non-null     object
 4   Unnamed: 4                 82 non-null     object
 5   Unnamed: 5                 12 non-null     object
 6   Unnamed: 6                 1 non-null      object
 7   Unnamed: 7                 83 non-null     object
 8   Unnamed: 8                 82 non-null     object
 9   Unnamed: 9                 82 non-null     object
 10  Unnamed: 10                82 non-null     object
 11  Unnamed: 11                82 non-null     object
 12  Unnamed: 12                82 non-null     object
 13  Unnamed: 13                82 non-null     object
 14  Unnamed: 14                82 non-null     object
 15  Unnamed: 15                82 non-null     object
 16  Unnamed: 16                82 non-null     object
 17  Unnamed: 17                82 non-null     object
 18  Unnamed: 18                82 non-null     object
 19  Unnamed: 19                12 non-null     object
 20  Unnamed: 20                0 non-null      float64
 21  Unnamed: 21                0 non-null      float64
 22  Unnamed: 22                0 non-null      float64
 23  Unnamed: 23                0 non-null      float64
 24  Unnamed: 24                0 non-null      float64
dtypes: float64(5), object(20)
memory usage: 17.7+ KB

In [13]:
desc.head(10)

,Unnamed: 0,Alteração de nomenclatura,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,Variável nova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Descontinuidade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N,Nome da Variável,Descrição da Variável,Tipo,Tam.,Categoria,Observação,"Coleta por ano (""s""=sim;""-""=não )",NaN,NaN,...,NaN,NaN,NaN,NaN,Notas sobre diferenças entre os anos,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09,10,11,...,17,18,19,20,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,NU_ANO_CENSO,Ano de referência do Censo da Educação Superior,Num,4,NaN,NaN,s,s,s,...,s,s,s,s,NaN,NaN,NaN,NaN,NaN,NaN
8,DADOS DA INSTITUIÇÃO DE ENSINO SUPERIOR (IES) ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2,NO_REGIAO_IES,Nome da região geográfica da sede administrati...,Char,20,NaN,NaN,s,s,s,...,s,s,s,s,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#### Eliminação dos atributos e linhas.
def eliminaAtributosELinhasArquivo(max):
    desc.drop(axis=1, labels='Unnamed: 0', inplace=True)
    for i in range(3,max):
        desc.drop(axis=1, labels='Unnamed: '+str(i), inplace=True)

    desc.dropna(how='any', inplace=True)
    desc.drop(axis=0, index=4, inplace=True)

def eliminaAtributosELinhasArquivo2():
    desc.drop(axis=1, labels='Unnamed: 0', inplace=True)
    for i in range(3,24):
        desc.drop(axis=1, labels='Unnamed: '+str(i), inplace=True)

    desc.dropna(how='any', inplace=True)
    desc.drop(axis=0, index=4, inplace=True)

if (arquivo1):
    eliminaAtributosELinhasArquivo(25)

    desc.columns=['ATRIBUTO','DESCRICAO']
    desc.reset_index(inplace=True, level=0, drop=True)
    desc.set_index('ATRIBUTO', drop=True, inplace=True)
    print(desc.loc['CO_REGIAO_IES']['DESCRICAO'])
else:
    eliminaAtributosELinhasArquivo(22)

    desc.columns=['ATRIBUTO','DESCRICAO']
    desc.reset_index(inplace=True, level=0, drop=True)
    desc.set_index('ATRIBUTO', drop=True, inplace=True)
    print(desc.loc['QT_MAT_MOB_ACADEMICA']['DESCRICAO'])

Código da região geográfica

In [15]:
desc

                                                                   DESCRICAO
ATRIBUTO
NU_ANO_CENSO                 Ano de referência do Censo da Educação Superior
NO_REGIAO_IES              Nome da região geográfica da sede administrati...
CO_REGIAO_IES                                    Código da região geográfica
NO_UF_IES                  Nome da Unidade da Federação da sede administr...
SG_UF_IES                  Sigla da Unidade da Federação da sede administ...
...                                                                      ...
QT_DOC_EX_INDIGENA         Quantidade de docentes em exercício - Cor/Raça...
QT_DOC_EX_COR_ND           Quantidade de docentes em exercício - Cor/Raça...
QT_DOC_EX_BRA              Quantidade de docentes em exercício - nacional...
QT_DOC_EX_EST              Quantidade de docentes em exercício - nacional...
QT_DOC_EX_COM_DEFICIENCIA  Quantidade de docentes em exercício - com defi...

[81 rows x 1 columns]

#### Gera o arquivo de descrição.

In [16]:
if (arquivo1):
    desc.to_csv('./Dados/cadastro_ies.csv',
                sep=';',
                header=True,
                encoding='latin-1',
                #compression='zip'
               )
    
    desc2=pd.read_csv('./Dados/cadastro_ies.csv',
                        sep=';',
                        header=0,
                        encoding='latin-1',)
    desc2.set_index('ATRIBUTO', drop=True, inplace=True)
    print(desc2)
else:
    desc.to_csv('./Dados/cadastro_cursos.csv',
                sep=';',
                header=True,
                encoding='latin-1',
                #compression='zip'
               )
    
    desc2=pd.read_csv('./Dados/cadastro_cursos.csv',
                        sep=';',
                        header=0,
                        encoding='latin-1',)
    desc2.set_index('ATRIBUTO', drop=True, inplace=True)
    print(desc2)

                                                                   DESCRICAO
ATRIBUTO
NU_ANO_CENSO                 Ano de referência do Censo da Educação Superior
NO_REGIAO_IES              Nome da região geográfica da sede administrati...
CO_REGIAO_IES                                    Código da região geográfica
NO_UF_IES                  Nome da Unidade da Federação da sede administr...
SG_UF_IES                  Sigla da Unidade da Federação da sede administ...
...                                                                      ...
QT_DOC_EX_INDIGENA         Quantidade de docentes em exercício - Cor/Raça...
QT_DOC_EX_COR_ND           Quantidade de docentes em exercício - Cor/Raça...
QT_DOC_EX_BRA              Quantidade de docentes em exercício - nacional...
QT_DOC_EX_EST              Quantidade de docentes em exercício - nacional...
QT_DOC_EX_COM_DEFICIENCIA  Quantidade de docentes em exercício - com defi...

[81 rows x 1 columns]

### Eof